# Generated by Django 4.2.10 on 2024-02-22 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_post_titledesc'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumpnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumpnail/'),
        ),
    ]
