# Generated by Django 4.2.10 on 2024-02-24 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_post_thumpnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='thumpnail',
        ),
    ]
