# Generated by Django 4.2.10 on 2024-03-18 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_submitwork_quatation'),
    ]

    operations = [
        migrations.AddField(
            model_name='submitwork',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.post'),
        ),
    ]
