# Generated by Django 4.2.10 on 2024-03-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_submitwork_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorrequest',
            name='accepted_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
