# Generated by Django 4.2.10 on 2024-03-12 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_auth_provider'),
        ('Notification', '0002_notification_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_notification', to='users.editorrequest'),
        ),
    ]
